volumes:
    db:

services:
    app:
        build:
            context: src/w
            dockerfile: ../docker/backend/Dockerfile
        env_file:
            - .docker_env
        volumes:
            - db:/app/database
